title: Kennedy Njuguna
#logo: https://media.licdn.com/dms/image/D4E03AQGYBc0bshe4Kw/profile-displayphoto-shrink_200_200/0/1689674094611?e=1707350400&v=beta&t=LlRvdaB75fXUU67HCpcv-Nz46fZVZ4fLf38T7j9I_0U
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
